FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
WORKDIR /app

FROM base AS builder
ARG NEXT_PUBLIC_API_URL=https://miniou.tusharcodes.tech/trpc
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm install -g turbo@^2.7.2
COPY . .
RUN turbo prune web --docker

FROM base AS installer
ARG NEXT_PUBLIC_API_URL=https://miniou.tusharcodes.tech/trpc
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
COPY --from=builder /app/out/full/ .
RUN pnpm turbo build --filter=web

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 --ingroup nodejs miniou

COPY --from=installer --chown=miniou:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=miniou:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=miniou:nodejs /app/apps/web/public ./apps/web/public

USER miniou
EXPOSE 3000
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
CMD ["node", "apps/web/server.js"]
